<?php
if ( !class_exists( 'UixSCFormCore' ) ) {
    return;
}

$sid     = ( isset( $_POST[ 'sectionID' ] ) ) ? $_POST[ 'sectionID' ] : -1;
$pid     = ( isset( $_POST[ 'postID' ] ) ) ? $_POST[ 'postID' ] : 0;
$cid     = ( isset( $_POST[ 'contentID' ] ) ) ? $_POST[ 'contentID' ] : 'content';
/**
 * Form ID
 */
$form_id = 'uix_sc_form_portfolio_grid';

/**
 * Form Type
 */
$form_type = [
    'list' => false
];


$args = 
	[
	
	
		array(
			'id'             => 'uix_sc_portfolio_grid_listitem_col',
			'title'          => __( 'Column', 'uix-shortcodes' ),
			'desc'           => '',
			'value'          => 3,
			'placeholder'    => '',
			'type'           => 'radio',
			'default'        => array(
									'4'  => '4',
									'3'  => '3',
									'2'  => '2',
								)
		
		),
		
		array(
			'id'             => 'uix_sc_portfolio_grid_filterable',
			'title'          => __( 'Filterable by Category', 'uix-shortcodes' ),
			'desc'           => '',
			'value'          => '',
			'placeholder'    => '',
			'type'           => 'checkbox',
			'default'        => array(
									'checked'  => false
								)
		
		
		),	
		

		array(
			'id'             => 'uix_sc_portfolio_grid_target',
			'title'          => __( 'Open link in new tab', 'uix-shortcodes' ),
			'desc'           => __( 'This option is valid when you use destination URL.', 'uix-shortcodes' ),
			'value'          => '',
			'placeholder'    => '',
			'type'           => 'checkbox',
			'default'        => array(
									'checked'  => false
								)
		
		
		),	
	
		
		array(
			'id'             => 'uix_sc_portfolio_grid_listitem_image_fillet',
			'title'          => __( 'Radius of Fillet Image', 'uix-shortcodes' ),
			'desc'           => '',
			'value'          => '0',
			'placeholder'    => '',
			'type'           => 'short-text',
			'default'        => array(
									'units'  => '%'
								)
		
		),	
	
		array(
			'id'             => 'uix_sc_portfolio_grid_listitem_class_prefix',
			'title'          => __( 'Class Prefix', 'uix-shortcodes' ),
			'desc'           => __( 'Prefix string attached to the classes of all elements generated by the portfolio, the default value is &quot;<strong>uix-sc-portfolio-</strong>&quot;.', 'uix-shortcodes' ),
			'value'          => 'uix-sc-portfolio-',
			'placeholder'    => '',
			'type'           => 'text'
		
		),
	 
		//------list begin
		array(
			'id'             => 'uix_sc_portfolio_grid_list',
			'title'          => __( 'List Item', 'uix-shortcodes' ),
			'desc'           => '',
			'value'          => '',
			'placeholder'    => '',
			'type'           => 'list',
			'default'        => array(
									'btn_text'                  => __( 'click here to add a item', 'uix-shortcodes' ),
									'clone_class'               => [ 
									
										array(
											'id'        => 'dynamic-row-uix_sc_portfolio_grid_listitem_image',
											'type'      => 'image'
										), 
										
										array(
											'id'        => 'dynamic-row-uix_sc_portfolio_grid_listitem_full_image',
											'type'      => 'image'
										), 		
									
										array(
											'id'        => 'dynamic-row-uix_sc_portfolio_grid_listitem_title',
											'type'      => 'text'
										), 		
										
										array(
											'id'        => 'dynamic-row-uix_sc_portfolio_grid_listitem_type',
											'type'      => 'text'
										), 								
										
										array(
											'id'        => 'dynamic-row-uix_sc_portfolio_grid_listitem_desc',
											'type'      => 'textarea'
										), 
										
										array(
											'id'              => 'dynamic-row-uix_sc_portfolio_grid_listitem_toggle',
											'type'            => 'toggle',
											'toggle_class'    => [ 'dynamic-row-uix_sc_portfolio_grid_url' ]
										), 	
															
							

									 ],
									'max'                       => 100
				                )
									
		),
		
		
			array(
				'id'             => 'uix_sc_portfolio_grid_listitem_image',
				'title'          => '',
				'desc'           => '',
				'value'          => '',
				'class'          => 'dynamic-row-uix_sc_portfolio_grid_listitem_image', /*class of list item */
				'placeholder'    => __( 'Thumbnail', 'uix-shortcodes' ),
				'type'           => 'image',
				'default'        => array(
										'remove_btn_text'  => __( 'Remove image', 'uix-shortcodes' ),
										'upload_btn_text'  => __( 'Upload', 'uix-shortcodes' ),
									)
			
			),	
			
			array(
				'id'             => 'uix_sc_portfolio_grid_listitem_full_image',
				'title'          => '',
				'desc'           => '',
				'value'          => '',
				'class'          => 'dynamic-row-uix_sc_portfolio_grid_listitem_full_image', /*class of list item */
				'placeholder'    => __( 'Full Preview', 'uix-shortcodes' ),
				'type'           => 'image',
				'default'        => array(
										'remove_btn_text'  => __( 'Remove image', 'uix-shortcodes' ),
										'upload_btn_text'  => __( 'Upload', 'uix-shortcodes' ),
									)
			
			),		
			
			
			array(
				'id'             => 'uix_sc_portfolio_grid_listitem_title',
				'title'          => '',
				'desc'           => '',
				'value'          => __( 'Project Title', 'uix-shortcodes' ),
				'class'          => 'dynamic-row-uix_sc_portfolio_grid_listitem_title', /*class of list item */
				'placeholder'    => '',
				'type'           => 'text'
			
			),
			
			array(
				'id'             => 'uix_sc_portfolio_grid_listitem_type',
				'title'          => '',
				'desc'           => '',
				'value'          => __( 'Category Name', 'uix-shortcodes' ),
				'class'          => 'dynamic-row-uix_sc_portfolio_grid_listitem_type', /*class of list item */
				'placeholder'    => '',
				'type'           => 'text'
			
			),	
			
			
	
			
			array(
				'id'             => 'uix_sc_portfolio_grid_listitem_desc',
				'title'          => '',
				'desc'           => '',
				'value'          => __( 'The description of this project.', 'uix-shortcodes' ),
				'class'          => 'dynamic-row-uix_sc_portfolio_grid_listitem_desc', /*class of list item */
				'placeholder'    => '',
				'type'           => 'textarea',
				'default'        => array(
										'row'     => 5,
										'format'  => true
									)
			
			),
			
			
			
			
	
			//------toggle begin
			array(
				'id'             => 'uix_sc_portfolio_grid_listitem_toggle',
				'title'          => '',
				'desc'           => '',
				'value'          => '',
				'class'          => 'dynamic-row-uix_sc_portfolio_grid_listitem_toggle', /*class of list item */
				'placeholder'    => '',
				'type'           => 'toggle',
				'default'        => array(
										'btn_text'      => __( 'set up destination URL with this project', 'uix-shortcodes' ),
										'toggle_class'  => [ 'dynamic-row-uix_sc_portfolio_grid_url' ]
									)
			
			),	
			
				array(
					'id'             => 'uix_sc_portfolio_grid_url',
					'title'          => '',
					'desc'           => '',
					'value'          => '',
					'class'          => 'toggle-row dynamic-row-uix_sc_portfolio_grid_url', /*class of toggle item */
					'placeholder'    => __( 'Destination URL', 'uix-shortcodes' ),
					'type'           => 'text'
				
				),
	
			
			//------toggle end
			
			
		
		//------list end
		
		


		
	
	]
;



$form_html = UixSCFormCore::add_form( $cid, $sid, $form_id, $form_type, $args, 'html' );
$form_js = UixSCFormCore::add_form( $cid, $sid, $form_id, $form_type, $args, 'js' );
$form_js_vars = UixSCFormCore::add_form( $cid, $sid, $form_id, $form_type, $args, 'js_vars' );

/**
 * Returns actions of javascript
 */

if ( $sid == -1 && is_admin() ) {
	$currentScreen = get_current_screen();
	if( $currentScreen->base === "post" || $currentScreen->base === "widgets" || $currentScreen->base === "customize" || UixSCFormCore::inc_str( $currentScreen->base, '_page_' ) ) {
	  
		/* List Item - Register clone vars ( step 1) */
		UixSCFormCore::reg_clone_vars( 'uix_sc_portfolio_grid_list', 
									  UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_listitem_image', $form_html )
									  .UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_listitem_full_image', $form_html )
									  .UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_listitem_title', $form_html )
									  .UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_listitem_type', $form_html )
									  .UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_listitem_desc', $form_html )
									  .UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_listitem_toggle', $form_html, 'toggle' )
									  .UixSCFormCore::dynamic_form_code( 'dynamic-row-uix_sc_portfolio_grid_url', $form_html, 'toggle-row' ) 
									 );	
		
		
		?>
		<script type="text/javascript">
		( function($) {
		'use strict';
			$( function() { 
				<?php echo UixSCFormCore::uixscform_callback( $form_js, $form_id, __( 'Insert Portfolio Section', 'uix-shortcodes' ) ); ?>					
				<?php echo UixSCFormCore::send_before( $form_js_vars, $form_id ); ?> 
				/*--**************** Custom shortcode begin ****************-- */
					/* List Item ( step 2)  */
					var list_num = 100;
					
			
					var show_list_item = '';
					for ( var i=0; i<=list_num; i++ ){
						
						var _uid = ( i == 0 ) ? '#' : '#'+i+'-',
							_image = $( _uid+'uix_sc_portfolio_grid_listitem_image' ).val(),
							_imagefull = $( _uid+'uix_sc_portfolio_grid_listitem_full_image' ).val(),
							_title = $( _uid+'uix_sc_portfolio_grid_listitem_title' ).val(),
							_type = $( _uid+'uix_sc_portfolio_grid_listitem_type' ).val(),
							_desc = $( _uid+'uix_sc_portfolio_grid_listitem_desc' ).val(),
							_item_url = ( $( _uid+'uix_sc_portfolio_grid_url' ).val() != '' ) ? encodeURI( $( _uid+'uix_sc_portfolio_grid_url' ).val() ) : '';	
								
								
						var _item_v_image = ( _image != undefined ) ? encodeURI( _image ) : '',
							_item_v_imagefull = ( _imagefull != undefined ) ? encodeURI( _imagefull ) : '',
							_item_v_title = ( _title != undefined ) ? uixscform_shortcodeHTMLEcode( _title ) : '',
							_item_v_type = ( _type != undefined ) ? uixscform_shortcodeHTMLEcode( _type ) : '',
							_item_v_desc = ( _desc != undefined ) ? uixscform_shortcodeTextareaPrint( _desc ) : '',
							_item_v_target = ( uix_sc_portfolio_grid_target === true ) ? 1 : 0,
							_item_v_filterable = ( uix_sc_portfolio_grid_filterable === true ) ? 1 : 0;
					
					
					
					
						 if ( _item_v_type == '<?php _e( 'Category Name', 'uix-shortcodes' ); ?>' ) _item_v_type = '';
						
						
						if ( _title != undefined ) {
							show_list_item += "<br>[uix_portfolio_item type='"+_item_v_type+"' title='"+_item_v_title+"' image='"+_item_v_image+"' fullimage='"+_item_v_imagefull+"' target='"+_item_v_target+"' url='"+_item_url+"']";
							show_list_item += "<br>[uix_portfolio_item_desc]"+ _item_v_desc +"[/uix_portfolio_item_desc]";					
							show_list_item += "<br>[/uix_portfolio_item]";
		
						}
						
				
					}
		
		
					code = "[uix_portfolio filterable='"+_item_v_filterable+"' classprefix='"+uixscform_shortcodeHTMLEcode( uix_sc_portfolio_grid_listitem_class_prefix )+"' col='"+uix_sc_portfolio_grid_listitem_col+"' imagefillet='"+uixscform_floatval( uix_sc_portfolio_grid_listitem_image_fillet )+"%']"+show_list_item+"<br>[/uix_portfolio]";

				/*--**************** Custom shortcode end ****************-- */
				<?php echo UixSCFormCore::send_after(); ?> 
		} ) ( jQuery );
		</script>
 
		<?php

	}
	
}


/**
 * Returns forms with ajax
 */
if ( $sid >= 0 && is_admin() ) {
	echo $form_html;	
}
